# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='can_ban',
            new_name='can_ban_flag',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='can_change_settings',
            new_name='can_change_settings_flag',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='can_delete_comments',
            new_name='can_delete_comments_flag',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='can_delete_posts',
            new_name='can_delete_posts_flag',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='can_edit_comments',
            new_name='can_edit_comments_flag',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='can_edit_posts',
            new_name='can_edit_posts_flag',
        ),
    ]
