# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='comment_condition',
            field=models.CharField(choices=[('A', 'Anyone can comment'), ('K', 'Only users with high karma can comment')], default='A', max_length=2, verbose_name='Who can comment in the blog'),
        ),
        migrations.AddField(
            model_name='blog',
            name='comment_karma_threshold',
            field=models.SmallIntegerField(default=0, verbose_name='Comment karma threshold'),
        ),
        migrations.AddField(
            model_name='blog',
            name='post_condition',
            field=models.CharField(choices=[('A', 'Anyone can add post'), ('K', 'Only users with high karma can add post')], default='A', max_length=2, verbose_name='Who can add posts'),
        ),
        migrations.AddField(
            model_name='blog',
            name='post_karma_threshold',
            field=models.SmallIntegerField(default=0, verbose_name='Post karma threshold'),
        ),
    ]
