# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 15:54
from __future__ import unicode_literals

import dj_markdown.datatype
import dj_markdown.extensions.autolink
import dj_markdown.extensions.automail
import dj_markdown.extensions.comment
import dj_markdown.extensions.escape
import dj_markdown.extensions.fenced_code
import dj_markdown.extensions.semi_sane_lists
import dj_markdown.extensions.strikethrough
import dj_markdown.models
import dj_markdown.renderer
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160305_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='_about_html',
            field=dj_markdown.models.HtmlCacheField(blank=True, editable=False, markdown_field=dj_markdown.models.MarkdownField(blank=True, cls_name='about_cls', default=dj_markdown.datatype.Markdown(html='', renderer=dj_markdown.renderer.BaseRenderer(extensions=['markdown.extensions.smarty', 'markdown.extensions.abbr', 'markdown.extensions.def_list', 'markdown.extensions.tables', 'markdown.extensions.smart_strong', dj_markdown.extensions.fenced_code.FencedCodeExtension(), dj_markdown.extensions.escape.EscapeHtmlExtension(), dj_markdown.extensions.semi_sane_lists.SemiSaneListExtension(), dj_markdown.extensions.strikethrough.StrikethroughExtension(), dj_markdown.extensions.autolink.AutolinkExtension(), dj_markdown.extensions.automail.AutomailExtension(), dj_markdown.extensions.comment.CommentExtension()]), source=''), markdown=dj_markdown.datatype.Markdown, renderer=dj_markdown.renderer.BaseRenderer(extensions=['markdown.extensions.smarty', 'markdown.extensions.abbr', 'markdown.extensions.def_list', 'markdown.extensions.tables', 'markdown.extensions.smart_strong', dj_markdown.extensions.fenced_code.FencedCodeExtension(), dj_markdown.extensions.escape.EscapeHtmlExtension(), dj_markdown.extensions.semi_sane_lists.SemiSaneListExtension(), dj_markdown.extensions.strikethrough.StrikethroughExtension(), dj_markdown.extensions.autolink.AutolinkExtension(), dj_markdown.extensions.automail.AutomailExtension(), dj_markdown.extensions.comment.CommentExtension()]), renderer_name='about_renderer', state_name='_about_state', verbose_name='About this blog'), null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='about',
            field=dj_markdown.models.MarkdownField(blank=True, cls_name='about_cls', default=dj_markdown.datatype.Markdown(html='', renderer=dj_markdown.renderer.BaseRenderer(extensions=['markdown.extensions.smarty', 'markdown.extensions.abbr', 'markdown.extensions.def_list', 'markdown.extensions.tables', 'markdown.extensions.smart_strong', dj_markdown.extensions.fenced_code.FencedCodeExtension(), dj_markdown.extensions.escape.EscapeHtmlExtension(), dj_markdown.extensions.semi_sane_lists.SemiSaneListExtension(), dj_markdown.extensions.strikethrough.StrikethroughExtension(), dj_markdown.extensions.autolink.AutolinkExtension(), dj_markdown.extensions.automail.AutomailExtension(), dj_markdown.extensions.comment.CommentExtension()]), source=''), markdown=dj_markdown.datatype.Markdown, renderer=dj_markdown.renderer.BaseRenderer(extensions=['markdown.extensions.smarty', 'markdown.extensions.abbr', 'markdown.extensions.def_list', 'markdown.extensions.tables', 'markdown.extensions.smart_strong', dj_markdown.extensions.fenced_code.FencedCodeExtension(), dj_markdown.extensions.escape.EscapeHtmlExtension(), dj_markdown.extensions.semi_sane_lists.SemiSaneListExtension(), dj_markdown.extensions.strikethrough.StrikethroughExtension(), dj_markdown.extensions.autolink.AutolinkExtension(), dj_markdown.extensions.automail.AutomailExtension(), dj_markdown.extensions.comment.CommentExtension()]), renderer_name='about_renderer', state_name='_about_state', verbose_name='About this blog'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('O', 'Owner'), ('M', 'Member'), ('B', 'Banned'), ('A', 'Administrator'), ('W', 'Waiting for approval')], default='M', max_length=2),
        ),
    ]
