# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 19:17
from __future__ import unicode_literals

import dj_markdown.datatype
import dj_markdown.extensions.autolink
import dj_markdown.extensions.automail
import dj_markdown.extensions.escape
import dj_markdown.extensions.fenced_code
import dj_markdown.extensions.semi_sane_lists
import dj_markdown.extensions.strikethrough
import dj_markdown.models
import dj_markdown.renderer
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20160305_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100, verbose_name='Caption')),
                ('is_draft', models.BooleanField(default=True, verbose_name='Is draft')),
                ('content', dj_markdown.models.MarkdownField(blank=True, cls_name='content_cls', default=dj_markdown.datatype.Markdown(html='', renderer=dj_markdown.renderer.BaseRenderer(extensions=['markdown.extensions.smarty', 'markdown.extensions.abbr', 'markdown.extensions.def_list', 'markdown.extensions.tables', 'markdown.extensions.smart_strong', dj_markdown.extensions.fenced_code.FencedCodeExtension(), dj_markdown.extensions.escape.EscapeHtmlExtension(), dj_markdown.extensions.semi_sane_lists.SemiSaneListExtension(), dj_markdown.extensions.strikethrough.StrikethroughExtension(), dj_markdown.extensions.autolink.AutolinkExtension(), dj_markdown.extensions.automail.AutomailExtension()]), source=''), markdown=dj_markdown.datatype.Markdown, renderer=dj_markdown.renderer.BaseRenderer(extensions=['markdown.extensions.smarty', 'markdown.extensions.abbr', 'markdown.extensions.def_list', 'markdown.extensions.tables', 'markdown.extensions.smart_strong', dj_markdown.extensions.fenced_code.FencedCodeExtension(), dj_markdown.extensions.escape.EscapeHtmlExtension(), dj_markdown.extensions.semi_sane_lists.SemiSaneListExtension(), dj_markdown.extensions.strikethrough.StrikethroughExtension(), dj_markdown.extensions.autolink.AutolinkExtension(), dj_markdown.extensions.automail.AutomailExtension()]), renderer_name='content_renderer', state_name='_content_state', verbose_name='Content')),
                ('_content_html', dj_markdown.models.HtmlCacheField(blank=True, editable=False, markdown_field=dj_markdown.models.MarkdownField(blank=True, cls_name='content_cls', default=dj_markdown.datatype.Markdown(html='', renderer=dj_markdown.renderer.BaseRenderer(extensions=['markdown.extensions.smarty', 'markdown.extensions.abbr', 'markdown.extensions.def_list', 'markdown.extensions.tables', 'markdown.extensions.smart_strong', dj_markdown.extensions.fenced_code.FencedCodeExtension(), dj_markdown.extensions.escape.EscapeHtmlExtension(), dj_markdown.extensions.semi_sane_lists.SemiSaneListExtension(), dj_markdown.extensions.strikethrough.StrikethroughExtension(), dj_markdown.extensions.autolink.AutolinkExtension(), dj_markdown.extensions.automail.AutomailExtension()]), source=''), markdown=dj_markdown.datatype.Markdown, renderer=dj_markdown.renderer.BaseRenderer(extensions=['markdown.extensions.smarty', 'markdown.extensions.abbr', 'markdown.extensions.def_list', 'markdown.extensions.tables', 'markdown.extensions.smart_strong', dj_markdown.extensions.fenced_code.FencedCodeExtension(), dj_markdown.extensions.escape.EscapeHtmlExtension(), dj_markdown.extensions.semi_sane_lists.SemiSaneListExtension(), dj_markdown.extensions.strikethrough.StrikethroughExtension(), dj_markdown.extensions.autolink.AutolinkExtension(), dj_markdown.extensions.automail.AutomailExtension()]), renderer_name='content_renderer', state_name='_content_state', verbose_name='Content'), null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'ordering': ('heading',),
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='icon',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Blog', verbose_name='Blog'),
        ),
    ]
