# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 22:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160305_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 6, 1, 16, 36, 459834)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='icon',
            field=models.CharField(blank=True, choices=[('aircraft', 'aircraft'), ('aircraft-take-off', 'aircraft take off'), ('aircraft-landing', 'aircraft landing'), ('area-graph', 'area graph'), ('archive', 'archive'), ('attachment', 'attachment'), ('awareness-ribbon', 'awareness ribbon'), ('back-in-time', 'back in time'), ('bar-graph', 'bar graph'), ('beamed-note', 'beamed note'), ('bell', 'bell'), ('blackboard', 'blackboard'), ('book', 'book'), ('bowl', 'bowl'), ('bookmarks', 'bookmarks'), ('box', 'box'), ('briefcase', 'briefcase'), ('brush', 'brush'), ('bucket', 'bucket'), ('bug', 'bug'), ('cake', 'cake'), ('camera', 'camera'), ('chat', 'chat'), ('clapperboard', 'clapperboard'), ('classic-computer', 'classic computer'), ('clipboard', 'clipboard'), ('cloud', 'cloud'), ('code', 'code'), ('cog', 'cog'), ('colours', 'colours'), ('compass', 'compass'), ('database', 'database'), ('dial-pad', 'dial pad'), ('documents', 'documents'), ('feather', 'feather'), ('flag', 'flag'), ('flash', 'flash'), ('flashlight', 'flashlight'), ('flat-brush', 'flat brush'), ('flow-branch', 'flow branch'), ('flower', 'flower'), ('folder', 'folder'), ('info-with-circle', 'info with circle'), ('infinity', 'infinity'), ('image', 'image'), ('hand', 'hand'), ('hair-cross', 'hair cross'), ('grid', 'grid'), ('graduation-cap', 'graduation cap'), ('globe', 'globe'), ('lab-flask', 'lab flask'), ('landline', 'landline'), ('keyboard', 'keyboard'), ('key', 'key'), ('layers', 'layers'), ('laptop', 'laptop'), ('leaf', 'leaf'), ('lifebuoy', 'lifebuoy'), ('light-bulb', 'light bulb'), ('light-up', 'light up'), ('line-graph', 'line graph'), ('location-pin', 'location pin'), ('modern-mic', 'modern mic'), ('moon', 'moon'), ('mic', 'mic'), ('medal', 'medal'), ('mail', 'mail'), ('magnet', 'magnet'), ('mouse-pointer', 'mouse pointer'), ('mouse', 'mouse'), ('network', 'network'), ('palette', 'palette'), ('new-message', 'new message'), ('new', 'new'), ('newsletter', 'newsletter'), ('note', 'note'), ('paper-plane', 'paper plane'), ('phone', 'phone'), ('rocket', 'rocket'), ('radio', 'radio'), ('print', 'print'), ('price-tag', 'price tag'), ('shop', 'shop'), ('suitcase', 'suitcase'), ('tablet-mobile-combo', 'tablet mobile combo'), ('thunder-cloud', 'thunder cloud'), ('ticket', 'ticket'), ('time-slot', 'time slot'), ('tools', 'tools'), ('traffic-cone', 'traffic cone'), ('tree', 'tree'), ('tv', 'tv'), ('video-camera', 'video camera'), ('video', 'video'), ('vinyl', 'vinyl'), ('voicemail', 'voicemail'), ('wallet', 'wallet'), ('warning', 'warning'), ('water', 'water')], max_length=100),
        ),
    ]
