# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-06 16:34
from __future__ import unicode_literals

import dj_markdown.datatype
import dj_markdown.extensions.autolink
import dj_markdown.extensions.automail
import dj_markdown.extensions.cut
import dj_markdown.extensions.escape
import dj_markdown.extensions.fenced_code
import dj_markdown.extensions.semi_sane_lists
import dj_markdown.extensions.strikethrough
import dj_markdown.models
import dj_markdown.renderer
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160306_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='_content_html',
            field=dj_markdown.models.HtmlCacheField(blank=True, editable=False, markdown_field=dj_markdown.models.MarkdownField(cls_name='content_cls', default=dj_markdown.datatype.Markdown(html='', renderer=dj_markdown.renderer.BaseRenderer(extensions=['markdown.extensions.smarty', 'markdown.extensions.abbr', 'markdown.extensions.def_list', 'markdown.extensions.tables', 'markdown.extensions.smart_strong', dj_markdown.extensions.fenced_code.FencedCodeExtension(), dj_markdown.extensions.escape.EscapeHtmlExtension(), dj_markdown.extensions.semi_sane_lists.SemiSaneListExtension(), dj_markdown.extensions.strikethrough.StrikethroughExtension(), dj_markdown.extensions.autolink.AutolinkExtension(), dj_markdown.extensions.automail.AutomailExtension(), dj_markdown.extensions.cut.CutExtension(anchor='cut')]), source=''), markdown=dj_markdown.datatype.Markdown, renderer=dj_markdown.renderer.BaseRenderer(extensions=['markdown.extensions.smarty', 'markdown.extensions.abbr', 'markdown.extensions.def_list', 'markdown.extensions.tables', 'markdown.extensions.smart_strong', dj_markdown.extensions.fenced_code.FencedCodeExtension(), dj_markdown.extensions.escape.EscapeHtmlExtension(), dj_markdown.extensions.semi_sane_lists.SemiSaneListExtension(), dj_markdown.extensions.strikethrough.StrikethroughExtension(), dj_markdown.extensions.autolink.AutolinkExtension(), dj_markdown.extensions.automail.AutomailExtension(), dj_markdown.extensions.cut.CutExtension(anchor='cut')]), renderer_name='content_renderer', state_name='_content_state', verbose_name='Content'), null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=dj_markdown.models.MarkdownField(cls_name='content_cls', default=dj_markdown.datatype.Markdown(html='', renderer=dj_markdown.renderer.BaseRenderer(extensions=['markdown.extensions.smarty', 'markdown.extensions.abbr', 'markdown.extensions.def_list', 'markdown.extensions.tables', 'markdown.extensions.smart_strong', dj_markdown.extensions.fenced_code.FencedCodeExtension(), dj_markdown.extensions.escape.EscapeHtmlExtension(), dj_markdown.extensions.semi_sane_lists.SemiSaneListExtension(), dj_markdown.extensions.strikethrough.StrikethroughExtension(), dj_markdown.extensions.autolink.AutolinkExtension(), dj_markdown.extensions.automail.AutomailExtension(), dj_markdown.extensions.cut.CutExtension(anchor='cut')]), source=''), markdown=dj_markdown.datatype.Markdown, renderer=dj_markdown.renderer.BaseRenderer(extensions=['markdown.extensions.smarty', 'markdown.extensions.abbr', 'markdown.extensions.def_list', 'markdown.extensions.tables', 'markdown.extensions.smart_strong', dj_markdown.extensions.fenced_code.FencedCodeExtension(), dj_markdown.extensions.escape.EscapeHtmlExtension(), dj_markdown.extensions.semi_sane_lists.SemiSaneListExtension(), dj_markdown.extensions.strikethrough.StrikethroughExtension(), dj_markdown.extensions.autolink.AutolinkExtension(), dj_markdown.extensions.automail.AutomailExtension(), dj_markdown.extensions.cut.CutExtension(anchor='cut')]), renderer_name='content_renderer', state_name='_content_state', verbose_name='Content'),
        ),
    ]
