language: python
services: mysql
python:
  - 2.7
  - 3.5
env:
  - DJANGO=1.10.1
    DJANGO_SETTINGS_MODULE="collective_blog.settings"
  - DJANGO=1.10
    DJANGO_SETTINGS_MODULE="collective_blog.settings"
  - DJANGO=1.9.7
    DJANGO_SETTINGS_MODULE="collective_blog.settings"
install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libmysqlclient-dev
  - pip install django==$DJANGO
  - pip install -r requirements.txt
  - pip install pep8
  - pip install mysqlclient
  - pip install -U coverage codacy-coverage
before_script:
  - mysql -e 'create database travis_ci_db;'
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - coverage run --source=. --omit=migrations --branch manage.py test
  - pep8 . --exclude=migrations --ignore=E501,E402,E731
after_success:
  - coverage combine ./collective_blog/.coverage
  - coverage report
  - coverage xml
  - python-codacy-coverage -r coverage.xml
sudo: true
