# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 10:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import dj_markdown.datatype
import dj_markdown.models
import dj_markdown.renderer


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Location')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('about', dj_markdown.models.MarkdownField(blank=True, cls_name='about_cls', default=dj_markdown.datatype.Markdown(html='', renderer=dj_markdown.renderer.BaseRenderer(), source=''), help_text='Tell us about yourself', markdown=dj_markdown.datatype.Markdown, renderer=dj_markdown.renderer.BaseRenderer(), state_name='_about_state', verbose_name='About')),
                ('_about_html', dj_markdown.models.HtmlCacheField(blank=True, editable=False, markdown_field=dj_markdown.models.MarkdownField(blank=True, cls_name='about_cls', default=dj_markdown.datatype.Markdown(html='', renderer=dj_markdown.renderer.BaseRenderer(), source=''), help_text='Tell us about yourself', markdown=dj_markdown.datatype.Markdown, renderer=dj_markdown.renderer.BaseRenderer(), state_name='_about_state', verbose_name='About'), null=True)),
                ('email_is_public', models.BooleanField(default=False, verbose_name='Show email')),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profiles',
                'ordering': ('user',),
                'verbose_name': 'Profile',
            },
        ),
    ]
