# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-21 14:14
from __future__ import unicode_literals

from django.db import migrations
import s_voting.models
import user.models.karma
import user.models.profile


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='karma',
            field=s_voting.models.VoteCacheField(default=0, query=user.models.profile._karma_cache_query, vote_model=user.models.karma.Karma),
        ),
    ]
