from django.utils.translation import ugettext_lazy as _

ICONS = (
    ('aircraft', _('aircraft')),
    ('aircraft-take-off', _('aircraft take off')),
    ('aircraft-landing', _('aircraft landing')),
    ('area-graph', _('area graph')),
    ('archive', _('archive')),
    ('attachment', _('attachment')),
    ('awareness-ribbon', _('awareness ribbon')),
    ('back-in-time', _('back in time')),
    ('bar-graph', _('bar graph')),
    ('beamed-note', _('beamed note')),
    ('bell', _('bell')),
    ('blackboard', _('blackboard')),
    ('book', _('book')),
    ('bowl', _('bowl')),
    ('bookmarks', _('bookmarks')),
    ('box', _('box')),
    ('briefcase', _('briefcase')),
    ('brush', _('brush')),
    ('bucket', _('bucket')),
    ('bug', _('bug')),
    ('cake', _('cake')),
    ('camera', _('camera')),
    ('chat', _('chat')),
    ('clapperboard', _('clapperboard')),
    ('classic-computer', _('classic computer')),
    ('clipboard', _('clipboard')),
    ('cloud', _('cloud')),
    ('code', _('code')),
    ('cog', _('cog')),
    ('colours', _('colours')),
    ('compass', _('compass')),
    ('database', _('database')),
    ('dial-pad', _('dial pad')),
    ('documents', _('documents')),
    ('feather', _('feather')),
    ('flag', _('flag')),
    ('flash', _('flash')),
    ('flashlight', _('flashlight')),
    ('flat-brush', _('flat brush')),
    ('flow-branch', _('flow branch')),
    ('flower', _('flower')),
    ('folder', _('folder')),
    ('info-with-circle', _('info with circle')),
    ('infinity', _('infinity')),
    ('image', _('image')),
    ('hand', _('hand')),
    ('hair-cross', _('hair cross')),
    ('grid', _('grid')),
    ('graduation-cap', _('graduation cap')),
    ('globe', _('globe')),
    ('lab-flask', _('lab flask')),
    ('landline', _('landline')),
    ('keyboard', _('keyboard')),
    ('key', _('key')),
    ('layers', _('layers')),
    ('laptop', _('laptop')),
    ('leaf', _('leaf')),
    ('lifebuoy', _('lifebuoy')),
    ('light-bulb', _('light bulb')),
    ('light-up', _('light up')),
    ('line-graph', _('line graph')),
    ('location-pin', _('location pin')),
    ('modern-mic', _('modern mic')),
    ('moon', _('moon')),
    ('mic', _('mic')),
    ('medal', _('medal')),
    ('mail', _('mail')),
    ('magnet', _('magnet')),
    ('mouse-pointer', _('mouse pointer')),
    ('mouse', _('mouse')),
    ('network', _('network')),
    ('palette', _('palette')),
    ('new-message', _('new message')),
    ('new', _('new')),
    ('newsletter', _('newsletter')),
    ('note', _('note')),
    ('paper-plane', _('paper plane')),
    ('phone', _('phone')),
    ('rocket', _('rocket')),
    ('radio', _('radio')),
    ('print', _('print')),
    ('price-tag', _('price tag')),
    ('shop', _('shop')),
    ('suitcase', _('suitcase')),
    ('tablet-mobile-combo', _('tablet mobile combo')),
    ('thunder-cloud', _('thunder cloud')),
    ('ticket', _('ticket')),
    ('time-slot', _('time slot')),
    ('tools', _('tools')),
    ('traffic-cone', _('traffic cone')),
    ('tree', _('tree')),
    ('tv', _('tv')),
    ('video-camera', _('video camera')),
    ('video', _('video')),
    ('vinyl', _('vinyl')),
    ('voicemail', _('voicemail')),
    ('wallet', _('wallet')),
    ('warning', _('warning')),
    ('water', _('water')),
)
