# -*- coding: utf-8 -*-
"""Django settings for collective_blog project

Generated by 'django-admin startproject' using Django 1.9.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/

"""

import os

if 'TRAVIS' in os.environ:
    from .travis_settings import *
elif 'HEROKU' in os.environ:
    from .prod_settings import *
elif 'DEV' in os.environ:
    from .dev_settings import *
else:
    raise RuntimeError('you should specify running environment '
                       '(use `export DEV=1` for debug, '
                       '`export HEROKU=1` for production)')
