# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-11 09:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import s_markdown.datatype
import s_markdown.extensions.autolink
import s_markdown.extensions.automail
import s_markdown.extensions.comment
import s_markdown.extensions.cut
import s_markdown.extensions.escape
import s_markdown.extensions.fenced_code
import s_markdown.extensions.semi_sane_lists
import s_markdown.extensions.strikethrough
import s_markdown.models
import s_markdown.renderer


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, unique=True)),
                ('about', s_markdown.models.MarkdownField(blank=True, cls_name='about_cls', default=s_markdown.datatype.Markdown(html='', renderer=s_markdown.renderer.BaseRenderer(extensions=['markdown.extensions.smarty', 'markdown.extensions.abbr', 'markdown.extensions.def_list', 'markdown.extensions.tables', 'markdown.extensions.smart_strong', s_markdown.extensions.fenced_code.FencedCodeExtension(), s_markdown.extensions.escape.EscapeHtmlExtension(), s_markdown.extensions.semi_sane_lists.SemiSaneListExtension(), s_markdown.extensions.strikethrough.StrikethroughExtension(), s_markdown.extensions.autolink.AutolinkExtension(), s_markdown.extensions.automail.AutomailExtension(), s_markdown.extensions.comment.CommentExtension()]), source=''), markdown=s_markdown.datatype.Markdown, renderer=s_markdown.renderer.BaseRenderer(extensions=['markdown.extensions.smarty', 'markdown.extensions.abbr', 'markdown.extensions.def_list', 'markdown.extensions.tables', 'markdown.extensions.smart_strong', s_markdown.extensions.fenced_code.FencedCodeExtension(), s_markdown.extensions.escape.EscapeHtmlExtension(), s_markdown.extensions.semi_sane_lists.SemiSaneListExtension(), s_markdown.extensions.strikethrough.StrikethroughExtension(), s_markdown.extensions.autolink.AutolinkExtension(), s_markdown.extensions.automail.AutomailExtension(), s_markdown.extensions.comment.CommentExtension()]), renderer_name='about_renderer', state_name='_about_state', verbose_name='About this blog')),
                ('_about_html', s_markdown.models.HtmlCacheField(blank=True, editable=False, markdown_field=s_markdown.models.MarkdownField(blank=True, cls_name='about_cls', default=s_markdown.datatype.Markdown(html='', renderer=s_markdown.renderer.BaseRenderer(extensions=['markdown.extensions.smarty', 'markdown.extensions.abbr', 'markdown.extensions.def_list', 'markdown.extensions.tables', 'markdown.extensions.smart_strong', s_markdown.extensions.fenced_code.FencedCodeExtension(), s_markdown.extensions.escape.EscapeHtmlExtension(), s_markdown.extensions.semi_sane_lists.SemiSaneListExtension(), s_markdown.extensions.strikethrough.StrikethroughExtension(), s_markdown.extensions.autolink.AutolinkExtension(), s_markdown.extensions.automail.AutomailExtension(), s_markdown.extensions.comment.CommentExtension()]), source=''), markdown=s_markdown.datatype.Markdown, renderer=s_markdown.renderer.BaseRenderer(extensions=['markdown.extensions.smarty', 'markdown.extensions.abbr', 'markdown.extensions.def_list', 'markdown.extensions.tables', 'markdown.extensions.smart_strong', s_markdown.extensions.fenced_code.FencedCodeExtension(), s_markdown.extensions.escape.EscapeHtmlExtension(), s_markdown.extensions.semi_sane_lists.SemiSaneListExtension(), s_markdown.extensions.strikethrough.StrikethroughExtension(), s_markdown.extensions.autolink.AutolinkExtension(), s_markdown.extensions.automail.AutomailExtension(), s_markdown.extensions.comment.CommentExtension()]), renderer_name='about_renderer', state_name='_about_state', verbose_name='About this blog'), null=True)),
                ('icon', models.CharField(blank=True, choices=[('aircraft', 'aircraft'), ('aircraft-take-off', 'aircraft take off'), ('aircraft-landing', 'aircraft landing'), ('area-graph', 'area graph'), ('archive', 'archive'), ('attachment', 'attachment'), ('awareness-ribbon', 'awareness ribbon'), ('back-in-time', 'back in time'), ('bar-graph', 'bar graph'), ('beamed-note', 'beamed note'), ('bell', 'bell'), ('blackboard', 'blackboard'), ('book', 'book'), ('bowl', 'bowl'), ('bookmarks', 'bookmarks'), ('box', 'box'), ('briefcase', 'briefcase'), ('brush', 'brush'), ('bucket', 'bucket'), ('bug', 'bug'), ('cake', 'cake'), ('camera', 'camera'), ('chat', 'chat'), ('clapperboard', 'clapperboard'), ('classic-computer', 'classic computer'), ('clipboard', 'clipboard'), ('cloud', 'cloud'), ('code', 'code'), ('cog', 'cog'), ('colours', 'colours'), ('compass', 'compass'), ('database', 'database'), ('dial-pad', 'dial pad'), ('documents', 'documents'), ('feather', 'feather'), ('flag', 'flag'), ('flash', 'flash'), ('flashlight', 'flashlight'), ('flat-brush', 'flat brush'), ('flow-branch', 'flow branch'), ('flower', 'flower'), ('folder', 'folder'), ('info-with-circle', 'info with circle'), ('infinity', 'infinity'), ('image', 'image'), ('hand', 'hand'), ('hair-cross', 'hair cross'), ('grid', 'grid'), ('graduation-cap', 'graduation cap'), ('globe', 'globe'), ('lab-flask', 'lab flask'), ('landline', 'landline'), ('keyboard', 'keyboard'), ('key', 'key'), ('layers', 'layers'), ('laptop', 'laptop'), ('leaf', 'leaf'), ('lifebuoy', 'lifebuoy'), ('light-bulb', 'light bulb'), ('light-up', 'light up'), ('line-graph', 'line graph'), ('location-pin', 'location pin'), ('modern-mic', 'modern mic'), ('moon', 'moon'), ('mic', 'mic'), ('medal', 'medal'), ('mail', 'mail'), ('magnet', 'magnet'), ('mouse-pointer', 'mouse pointer'), ('mouse', 'mouse'), ('network', 'network'), ('palette', 'palette'), ('new-message', 'new message'), ('new', 'new'), ('newsletter', 'newsletter'), ('note', 'note'), ('paper-plane', 'paper plane'), ('phone', 'phone'), ('rocket', 'rocket'), ('radio', 'radio'), ('print', 'print'), ('price-tag', 'price tag'), ('shop', 'shop'), ('suitcase', 'suitcase'), ('tablet-mobile-combo', 'tablet mobile combo'), ('thunder-cloud', 'thunder cloud'), ('ticket', 'ticket'), ('time-slot', 'time slot'), ('tools', 'tools'), ('traffic-cone', 'traffic cone'), ('tree', 'tree'), ('tv', 'tv'), ('video-camera', 'video camera'), ('video', 'video'), ('vinyl', 'vinyl'), ('voicemail', 'voicemail'), ('wallet', 'wallet'), ('warning', 'warning'), ('water', 'water')], max_length=100)),
                ('type', models.CharField(choices=[('O', 'Open'), ('P', 'Private')], default='0', max_length=2, verbose_name='Type of the blog')),
                ('join_condition', models.CharField(choices=[('A', 'Anyone can join'), ('K', 'Only users with high karma can join'), ('I', 'Manual approval required')], default='A', max_length=2, verbose_name='Who can join the blog')),
                ('join_karma_threshold', models.SmallIntegerField(default=0, verbose_name='Join karma threshold')),
                ('post_condition', models.CharField(choices=[('A', 'Anyone can add post'), ('K', 'Only users with high karma can add post')], default='A', max_length=2, verbose_name='Who can add posts')),
                ('post_membership_required', models.BooleanField(default=False, verbose_name='Require membership to write posts')),
                ('post_karma_threshold', models.SmallIntegerField(default=0, verbose_name='Post karma threshold')),
                ('comment_condition', models.CharField(choices=[('A', 'Anyone can comment'), ('K', 'Only users with high karma can comment')], default='A', max_length=2, verbose_name='Who can comment in the blog')),
                ('comment_membership_required', models.BooleanField(default=False, verbose_name='Require membership to write comments')),
                ('comment_karma_threshold', models.SmallIntegerField(default=0, verbose_name='Comment karma threshold')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ban_expiration', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('O', 'Owner'), ('M', 'Member'), ('B', 'Banned'), ('A', 'Administrator'), ('W', 'Waiting for approval')], default='M', max_length=2)),
                ('can_change_settings_flag', models.BooleanField(default=False, verbose_name="Can change blog's settings")),
                ('can_edit_posts_flag', models.BooleanField(default=False, verbose_name='Can edit posts')),
                ('can_delete_posts_flag', models.BooleanField(default=False, verbose_name='Can delete posts')),
                ('can_edit_comments_flag', models.BooleanField(default=False, verbose_name='Can edit comments')),
                ('can_delete_comments_flag', models.BooleanField(default=False, verbose_name='Can delete comments')),
                ('can_ban_flag', models.BooleanField(default=False, verbose_name='Can ban a member')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collective_blog.Blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100, verbose_name='Caption')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, unique=True)),
                ('is_draft', models.BooleanField(default=True, verbose_name='Is draft')),
                ('content', s_markdown.models.MarkdownField(cls_name='content_cls', default=s_markdown.datatype.Markdown(html='', renderer=s_markdown.renderer.BaseRenderer(extensions=['markdown.extensions.smarty', 'markdown.extensions.abbr', 'markdown.extensions.def_list', 'markdown.extensions.tables', 'markdown.extensions.smart_strong', s_markdown.extensions.fenced_code.FencedCodeExtension(), s_markdown.extensions.escape.EscapeHtmlExtension(), s_markdown.extensions.semi_sane_lists.SemiSaneListExtension(), s_markdown.extensions.strikethrough.StrikethroughExtension(), s_markdown.extensions.autolink.AutolinkExtension(), s_markdown.extensions.automail.AutomailExtension(), s_markdown.extensions.cut.CutExtension(anchor='cut')]), source=''), markdown=s_markdown.datatype.Markdown, renderer=s_markdown.renderer.BaseRenderer(extensions=['markdown.extensions.smarty', 'markdown.extensions.abbr', 'markdown.extensions.def_list', 'markdown.extensions.tables', 'markdown.extensions.smart_strong', s_markdown.extensions.fenced_code.FencedCodeExtension(), s_markdown.extensions.escape.EscapeHtmlExtension(), s_markdown.extensions.semi_sane_lists.SemiSaneListExtension(), s_markdown.extensions.strikethrough.StrikethroughExtension(), s_markdown.extensions.autolink.AutolinkExtension(), s_markdown.extensions.automail.AutomailExtension(), s_markdown.extensions.cut.CutExtension(anchor='cut')]), renderer_name='content_renderer', state_name='_content_state', verbose_name='Content')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('_content_html', s_markdown.models.HtmlCacheField(blank=True, editable=False, markdown_field=s_markdown.models.MarkdownField(cls_name='content_cls', default=s_markdown.datatype.Markdown(html='', renderer=s_markdown.renderer.BaseRenderer(extensions=['markdown.extensions.smarty', 'markdown.extensions.abbr', 'markdown.extensions.def_list', 'markdown.extensions.tables', 'markdown.extensions.smart_strong', s_markdown.extensions.fenced_code.FencedCodeExtension(), s_markdown.extensions.escape.EscapeHtmlExtension(), s_markdown.extensions.semi_sane_lists.SemiSaneListExtension(), s_markdown.extensions.strikethrough.StrikethroughExtension(), s_markdown.extensions.autolink.AutolinkExtension(), s_markdown.extensions.automail.AutomailExtension(), s_markdown.extensions.cut.CutExtension(anchor='cut')]), source=''), markdown=s_markdown.datatype.Markdown, renderer=s_markdown.renderer.BaseRenderer(extensions=['markdown.extensions.smarty', 'markdown.extensions.abbr', 'markdown.extensions.def_list', 'markdown.extensions.tables', 'markdown.extensions.smart_strong', s_markdown.extensions.fenced_code.FencedCodeExtension(), s_markdown.extensions.escape.EscapeHtmlExtension(), s_markdown.extensions.semi_sane_lists.SemiSaneListExtension(), s_markdown.extensions.strikethrough.StrikethroughExtension(), s_markdown.extensions.autolink.AutolinkExtension(), s_markdown.extensions.automail.AutomailExtension(), s_markdown.extensions.cut.CutExtension(anchor='cut')]), renderer_name='content_renderer', state_name='_content_state', verbose_name='Content'), null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collective_blog.Blog', verbose_name='Blog')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='PostVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.SmallIntegerField(choices=[(1, '+1'), (-1, '-1')])),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='collective_blog.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_for_collective_blog_postvote', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='members',
            field=models.ManyToManyField(editable=False, through='collective_blog.Membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='postvote',
            unique_together=set([('user', 'object')]),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set([('user', 'blog')]),
        ),
    ]
