# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collective_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post_condition',
            field=models.CharField(choices=[('A', 'Anyone can add posts'), ('K', 'Only users with high karma can add posts')], default='K', max_length=2, verbose_name='Who can add posts'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='post_membership_required',
            field=models.BooleanField(default=True, verbose_name='Require membership to write posts'),
        ),
        migrations.AlterField(
            model_name='post',
            name='heading',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
