# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-06 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collective_blog', '0002_auto_20160424_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='color',
            field=models.CharField(choices=[('gray', 'Gray'), ('black', 'Black'), ('blue', 'Blue'), ('orange', 'Orange'), ('purple', 'Purple'), ('marshy', 'Marshy'), ('turquoise', 'Turquoise'), ('red', 'Red'), ('yellow', 'Yellow'), ('green', 'Green')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='membership',
            name='ban_expiration',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
