# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-08 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collective_blog', '0004_post_rating_cache'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='rating_cache',
            new_name='rating',
        ),
    ]
