# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-08 17:12
from __future__ import unicode_literals

import collective_blog.models.blog
import collective_blog.models.post
from django.db import migrations
import s_voting.models


class Migration(migrations.Migration):

    dependencies = [
        ('collective_blog', '0005_auto_20160608_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='overall_posts_rating',
            field=s_voting.models.VoteCacheField(default=0, query=collective_blog.models.blog._overall_posts_rating_cache_query, vote_model=collective_blog.models.post.PostVote),
        ),
    ]
