# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-08 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collective_blog', '0006_membership_overall_posts_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('O', 'Owner'), ('M', 'Member'), ('B', 'Banned'), ('A', 'Administrator'), ('W', 'Waiting for approval'), ('L', 'Left the blog'), ('LB', 'Left the blog (banned)')], default='M', max_length=2),
        ),
    ]
