# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collective_blog', '0006_auto_20160622_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_hidden_by_moderator',
            field=models.BooleanField(default=False, verbose_name='Is hidden by moderator'),
        ),
    ]
