# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-08 23:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collective_blog', '0007_auto_20160609_0212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='can_edit_comments_flag',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='can_edit_posts_flag',
        ),
    ]
