# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-09 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collective_blog', '0008_auto_20160609_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='can_accept_new_users_flag',
            field=models.BooleanField(default=False, verbose_name='Can accept new users'),
        ),
    ]
