# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-09 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collective_blog', '0009_membership_can_accept_new_users_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='can_manage_permissions_flag',
            field=models.BooleanField(default=False, verbose_name='Can accept new users'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='color',
            field=models.CharField(choices=[('gray', 'Gray'), ('black', 'Black'), ('blue', 'Blue'), ('orange', 'Orange'), ('purple', 'Purple'), ('marshy', 'Marshy'), ('turquoise', 'Turquoise'), ('red', 'Red'), ('yellow', 'Yellow'), ('green', 'Green')], default='gray', max_length=10),
        ),
    ]
