# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collective_blog', '0003_auto_20160622_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Is hidden'),
        ),
    ]
