# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collective_blog', '0007_comment_is_hidden_by_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='post_admin_required',
            field=models.BooleanField(default=False, verbose_name='Only admins can write posts'),
        ),
    ]
