# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('collective_blog', '0011_auto_20160823_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags', through='collective_blog.TaggedItem', to='collective_blog.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='taggeditem',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collective_blog_taggeditem_items', to='collective_blog.Tag'),
        ),
    ]
